server:
  port: 8080
spring:
  application:
    name: liveloadjar
  datasource:
    primary:
      jdbc-url: jdbc:mariadb://192.168.93.128:3306/liveload?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: mari33#06adb
    quartz:
      jdbc-url: jdbc:mariadb://192.168.93.128:3306/quartz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: mari33#06adb
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    #    properties:
  #      hibernate:
  #        hbm2ddl:
  #          auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    livereload:
      enabled: true

org:
  example:
    plugin:
      path:
        tmp: "E:/data/liveload-test/tmp"
        target: "E:/data/liveload-test"
        deleted: "E:/data/liveload-test/deleted"
    package: org.example.proccesser
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html


