server:
  port: 8080
spring:
  application:
    name: simpleJob
  datasource:
    primary:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;NON_KEYWORDS=GROUP
      driver-class-name: org.h2.Driver
      username: sa
      password: test#123
    quartz:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;NON_KEYWORDS=GROUP
      driver-class-name: org.h2.Driver
      username: sa
      password: test#123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    #    properties:
  #      hibernate:
  #        hbm2ddl:
  #          auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      data-locations:
        - classpath:sql/data.sql
      schema-locations:
        - classpath:sql/schema-task.sql
        - classpath:sql/schema-quartz.sql
      platform: org.hibernate.dialect.H2Dialect
      mode: embedded
      encoding: UTF-8

org:
  example:
    package: org.example.proccessor
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

