server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://192.168.93.128:3306/liveload?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: mari33#06adb
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true
    #    properties:
  #      hibernate:
  #        hbm2ddl:
  #          auto: update


